### ISSUE TITLE
Setup release scripts and tests for the structure_test image.

### ISSUE THREAD

**Issue by dlorenc** [GoogleCloudPlatform/runtimes-common#10]

**Comment by dlorenc** [comment]
cc @sharifelgamal
@nkubala

**Comment by nkubala** [comment]
@sharifelgamal can you confirm this is fixed by https://github.com/GoogleCloudPlatform/runtimes-common/pull/66 in conjunction with internal release process.

**Comment by sharifelgamal** [comment]
Yes, this should be closed.
