### ISSUE TITLE
For integration tests, document Dockerfile requirements

### ISSUE THREAD

**Issue by aslo** [GoogleCloudPlatform/runtimes-common#112]
What template variables are available to use in the Dockerfile? Looking at the code, I see that ${STAGING_IMAGE} is replaced with the built image name. Are there others?

**Comment by nkubala** [comment]
I updated the docs; sorry this wasn't very clear, but the only thing that should be templated in the sample application Dockerfile is the base image (so it can be dynamically substituted in once it's built in the cloud build). We don't currently support any other template variables, though if there are some you want feel free to open issues and we can look into it.

**Comment by aslo** [comment]
:+1:
