### ISSUE TITLE
Add Cloud Debugger test to Integration Testing Framework

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/runtimes-common#119]
@nkubala

**Comment by meltsufin** [comment]
Can we raise the priority of this? We hit another issue integrating with the debugger recently. This would've helped catching it early.

**Comment by nkubala** [comment]
Shooting to have this finished by the end of the quarter. I'll keep you posted.

**Comment by meltsufin** [comment]
Thanks! Looking forward to it!

**Comment by meltsufin** [comment]
@nkubala Any updates on this? Thanks!

**Comment by nkubala** [comment]
I have most of the code written, but still working through some kinks. Hard to give a timeline but it should be done soon.

**Comment by meltsufin** [comment]
Anything new on this one? We're investigating an issue with the new Java 9 runtime where the Cloud Debugger doesn't seem to be working, and this test would've helped us detect it earlier. Thanks!

**Comment by nkubala** [comment]
@meltsufin Sorry for the lack of updates here, didn't mean to ignore you :( I got sidetracked with other work and never got around to picking this back up. Bumping the priority of this

**Comment by nkubala** [comment]
Update: our team has passed off most runtimes-related work, so I'm going to close this issue since there aren't plans to add this to the integration testing framework for now.
