### ISSUE TITLE
integration_test logging: documentation out of date

### ISSUE THREAD

**Issue by ofrobots** [GoogleCloudPlatform/runtimes-common#134]
The [doc](https://github.com/GoogleCloudPlatform/runtimes-common/blob/master/integration_tests/README.md) states that the POST data would:

* hit `/logging_standard`. Instead I see the `/logging` endpoint being hit.
* Have `token` and `level` request parameters. I see `token` and `log_name`.

**Comment by ofrobots** [comment]
Also, I am not sure what the difference between the standard and custom logging modules is supposed to be.

**Comment by nkubala** [comment]
Sorry, I just needed to release an updated version of the integration test image (the documentation is newer than the image). I'll update the docs to be a bit more descriptive of the difference between the two.
