### ISSUE TITLE
structure_test error: chdir to cwd ("/app") set in config.json failed

### ISSUE THREAD

**Issue by duggelz** [GoogleCloudPlatform/runtimes-common#234]
I'm seeing this message intermittently.  The image being tested, `gcr.io/google-appengine/python:latest` has `/app` as a symlink to `/home/vmagent/app`, so maybe that's a problem?  But it's been that way for more than a year.

Error from Kokoro log:
```
Step #3: 6bcb0d4f1d1d: Pull complete
Step #3: Digest: sha256:eaa3d87858f06447663029e08b6d5166c73d40b9a7b7880e5eea9a57dd762faf
Step #3: Status: Downloaded newer image for gcr.io/gcp-runtimes/structure_test:latest
Starting Step #3
Step #3: container_linux.go:247: starting container process caused "chdir to cwd (\"/app\") set in config.json failed: no such file or directory"
Step #3: docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "chdir to cwd (\"/app\") set in config.json failed: no such file or directory".
Finished Step #3
ERROR
ERROR: build step "gcr.io/gcp-runtimes/structure_test:latest" failed: exit status 127
```

cloudbuild.yaml: https://github.com/GoogleCloudPlatform/python-runtime/blob/master/cloudbuild.yaml#L14

It also happened while building on my machine yesterday, but I can't remember the specifics, and I can't replicate it locally.

**Comment by duggelz** [comment]
FYI @nkubala

**Comment by nkubala** [comment]
@duggelz can you verify that this issue is either fixed or is still reproducible? The structure tests have since gone through a major overhaul (including being moved to their own [separate repo](https://github.com/GoogleCloudPlatform/container-structure-test)) so I'd like to either close this issue or move it over and investigate further.

**Comment by duggelz** [comment]
Not reproducible
