### ISSUE TITLE
Remove Docker dependency in iDiff tool

### ISSUE THREAD

**Issue by nkubala** [GoogleCloudPlatform/runtimes-common#244]
We should try and remove the dependency on having a working Docker daemon on the host machine for the tool. It should be possible to use the Docker Registry API directly to do things like image push/pull and history.

**Comment by abbytiz** [comment]
Options explored:[ docker-registry-client](https://github.com/heroku/docker-registry-client), [containers/image](https://github.com/containers/image)

[Notes](https://docs.google.com/document/d/1YcENo7zH3cBLXnG2kCBA32Z9LYjthGhOHaZnLoUylFs/edit) from attempts
