### ISSUE TITLE
Document basic usage of iDiff tool in README.md

### ISSUE THREAD

**Issue by nkubala** [GoogleCloudPlatform/runtimes-common#255]

**Comment by aaron-prindle** [comment]
The README.md should also include examples for how to use the tool with automation (parsing json or the output) as well as how to use the tool in a Travis-CI pipeline.  Example: Change Dockerfile in Github, Travis build image, does some verification using iDiff on what has changed and perhaps a test on what is allowable (for example, a test that the curl package still exists or that the container is less than Xmb)

**Comment by abbytiz** [comment]
#265 has working draft.  Not all examples included yet.
