### ISSUE TITLE
Make config_integrity_test more fault tolerant

### ISSUE THREAD

**Issue by sharifelgamal** [GoogleCloudPlatform/runtimes-common#279]
Right now the config integrity test lists all images for a specific repository and loops through them to make sure a given digest exists. We should just run a describe on the digest and make sure it comes back clean.

**Comment by nkubala** [comment]
Do we still plan on doing this? Has the "temp" fix from #281 been good enough?

**Comment by sharifelgamal** [comment]
This was fixed in the larger reconciletags refactor.
