### ISSUE TITLE
Add support for filtering by resource.type in logging integration tests

### ISSUE THREAD

**Issue by nkubala** [GoogleCloudPlatform/runtimes-common#311]
If we could figure out which environment the test application is running in (unclear if this is possible), then we could add the corresponding `resource.type` filter into the request for log entries, significantly reducing the time the query would take.

cc @balopat

**Comment by balopat** [comment]
How about asking the application to implement an endpoint that returns the preferred logging environment?

**Comment by nkubala** [comment]
looking into using the [metadata server](https://cloud.google.com/compute/docs/storing-retrieving-metadata) to do this. I need to do this for running the tests on GKE anyway

**Comment by nkubala** [comment]
Fixed through `/environment` endpoint being added to integration test sample application spec.
