### ISSUE TITLE
structure_test should support "args" in addition to "command"

### ISSUE THREAD

**Issue by mattmoor** [GoogleCloudPlatform/runtimes-common#317]
K8s uses the terms "command" and "args" in place of "entrypoint" and "cmd".

`structure_test` should support a mode for "Expected Output" where the entrypoint is invoked and arguments are passed to it.

Without it, there is no way to test `entrypoint` is configured properly.

**Comment by mattmoor** [comment]
@dlorenc FYI

**Comment by dlorenc** [comment]
Looks like GitHub got tricked by the "partially fixes" text in the PR.

**Comment by nkubala** [comment]
This was fixed via the PR referenced here, and by the addition of the metadata tests which directly test the entrypoint configuration.
