### ISSUE TITLE
Make logging of failed structure tests more clear

### ISSUE THREAD

**Issue by nkubala** [GoogleCloudPlatform/runtimes-common#53]

**Comment by nkubala** [comment]
one way might be to write a small logging wrapper around golang testing.T logging that spits out more verbose output.

**Comment by duggelz** [comment]
For a test with multiple config files, it's quite clumsy to determine which step in which file is failing.  Printing out the name of each config file before executing its steps would be very helpful.

E.g. the following has a zillion lines out output, and I have to step through the config files one by one to localize the error.

```
- name: gcr.io/gcp-runtimes/structure_test
  args: [
    '-i', '${IMAGE_NAME}',
    '--config', '/workspace/tests/virtualenv/virtualenv_default.yaml',
    '--config', '/workspace/tests/virtualenv/virtualenv_python34.yaml',
    '--config', '/workspace/tests/virtualenv/virtualenv_python35.yaml',
    '--config', '/workspace/tests/no-virtualenv/no-virtualenv.yaml',
    '--config', '/workspace/tests/python2-libraries/python2-libraries.yaml',
    '--config', '/workspace/tests/python3-libraries/python3-libraries.yaml',
    '-v'
  ]
```

**Comment by aslo** [comment]
👍 

It would also be nice to have slightly more verbose output even for successful runs. Something like "N tests successfully completed" makes it easy to know that my tests have actually run, i.e. nothing was misconfigured.
