### ISSUE TITLE
add an option for ftl.par to return a file

### ISSUE THREAD

**Issue by oyiptong** [GoogleCloudPlatform/runtimes-common#532]
Add an option for `ftl.par` to return a docker image as a file in a specified directory instead of an upload to GCR

**Comment by oyiptong** [comment]
an example:

```
--output-file [PATH_TO_OUTPUT_IMAGE]
```

**Comment by aaron-prindle** [comment]
This is actually already supported, the ftl.par has a flag `--output-path` that when set saves the output image as a tar to the specified path
https://github.com/GoogleCloudPlatform/runtimes-common/blob/master/ftl/common/args.py#L85-L90

Feel free to re-open this is there is still an issue using this.
