### ISSUE TITLE
Python version does not seem to be parsed correctly?

### ISSUE THREAD

**Issue by rahulrv1980** [GoogleCloudPlatform/runtimes-common#600]
Step #1 - "ftl": INFO starting: check python version
Step #1 - "ftl": INFO `python version` full cmd:
Step #1 - "ftl": /opt/python3.7/bin/python3.7 --version
Step #1 - "ftl": INFO `python version` stdout:
Step #1 - "ftl": Python 3.7.0b3 (default, Apr 23 2018, 15:31:36) 
Step #1 - "ftl": [GCC 7.3.0]
Step #1 - "ftl": 
Step #1 - "ftl": INFO `python version` stderr:
Step #1 - "ftl": 
Step #1 - "ftl": INFO check python version took 0 seconds
Step #1 - "ftl": INFO [CACHE][HIT] v1:PYTHON (interpreter)->dcf4a6d90b1b8521d23dba0071c481389c90d53e7dd278845fce6bca52ef0a89
Step #1 - "ftl": INFO checking_cached_interpreter_layer took 0 seconds

**Comment by aaron-prindle** [comment]
talked offline, closing
