### ISSUE TITLE
Execute the user specified entrypoint using "sh -c"

### ISSUE THREAD

**Issue by rahulrv1980** [GoogleCloudPlatform/runtimes-common#631]
The user may specify an entrypoint like 'gunicorn main:app --port $PORT" and the env variable $PORT will not be expanded although the env variable is present in the docker image. it would be good to execute this via a shell to allow for shell expansion.

**Comment by rahulrv1980** [comment]
ideally, this is controllable via a flag.

**Comment by aaron-prindle** [comment]
fixed w/ https://github.com/GoogleCloudPlatform/runtimes-common/pull/632, closing
