### ISSUE TITLE
Container Registry build history shows "Build successful with  FTLfail but 

### ISSUE THREAD

**Issue by estrellis** [GoogleCloudPlatform/runtimes-common#634]
I see this problem when installing mysqlclient on a machine without mysql_config installed

Step #1 - "ftl": Collecting mysqlclient (from -r /dev/stdin (line 3))
Step #1 - "ftl": Downloading https://files.pythonhosted.org/packages/6f/86/bad31f1c1bb0cc99e88ca2adb7cb5c71f7a6540c1bb001480513de76a931/mysqlclient-1.3.12.tar.gz (89kB)
Step #1 - "ftl": Complete output from command python setup.py egg_info:
Step #1 - "ftl": /bin/sh: 1: mysql_config: not found
Step #1 - "ftl": Traceback (most recent call last):
Step #1 - "ftl": File "<string>", line 1, in <module>
Step #1 - "ftl": File "/tmp/pip-build-byct3c89/mysqlclient/setup.py", line 17, in <module>
Step #1 - "ftl": metadata, options = get_config()
Step #1 - "ftl": File "/tmp/pip-build-byct3c89/mysqlclient/setup_posix.py", line 44, in get_config
Step #1 - "ftl": libs = mysql_config("libs_r")
Step #1 - "ftl": File "/tmp/pip-build-byct3c89/mysqlclient/setup_posix.py", line 26, in mysql_config
Step #1 - "ftl": raise EnvironmentError("%s not found" % (mysql_config.path,))
Step #1 - "ftl": OSError: mysql_config not found

**Comment by dlorenc** [comment]
Hey @estrellis,

Could you attach the full requirements.txt used to trigger this? I think this is probably expected, and you'll need to install mysql_config in the container used to run FTL to work around this.

**Comment by estrellis** [comment]
Step #1 - "ftl": INFO FTL version python-v0.3.1
Step #1 - "ftl": INFO Beginning FTL build for python

**Comment by dlorenc** [comment]
It looks like there hasn't been a release since the fix went in. Let's get a 0.3.2 out Monday.
