### ISSUE TITLE
FTL: Feature: Add support for Go 1.11 and vgo

### ISSUE THREAD

**Issue by sbuss** [GoogleCloudPlatform/runtimes-common#683]
With the addition of vgo and `go.mod` files, FTL becomes useful for speeding up Go builds. `go.mod` defines the set of dependencies for a Go package, rather than requiring that all of the code be locally staged before running the build.

See https://github.com/golang/go/wiki/vgo for details on how vgo works.

CC @broady @zombiezen

**Comment by sbuss** [comment]
Note: technically, vgo will be experimental until Go 1.12, but it will be available for use starting with Go 1.11.

**Comment by dlorenc** [comment]
Can you explain anymore? I don't think FTL can do anything meaningful for Go/VGO still. The dependencies will still need to be fetched to the build VM each time before each build.

**Comment by sbuss** [comment]
`vgo` will allow users to specify their dependencies in a `go.mod` file, akin to, eg, `Gemfile.lock`. Upon running `go build` the dependencies declared in `go.mod` will be fetched via `go get <package>` and then a normal build will commence.

This allows us an opportunity to cache the dependencies in an FTL-compatible way. Rather than uploading the source of all of their dependencies, users will just upload their app and their `go.mod` file and we will fetch all of the dependencies into the builder. `go.mod` files will look like this:

```
module "github.com/sbuss/myapp"

require (
	"github.com/example/foo" v1.1.0
	"github.com/example/bar" v0.8.0
)
```

See https://github.com/golang/go/wiki/vgo and https://github.com/golang/go/wiki/vgo-user-guide for a more detailed explanation of how `vgo` works.

Also, this is a great blog post that talks about the internal details relevant to FTL: https://www.wolfe.id.au/2018/03/01/diving-into-vgo-from-the-golang-project/

**Comment by dlorenc** [comment]
> This allows us an opportunity to cache the dependencies in an FTL-compatible way

Can you explain this a little more? Where would the dependencies be cached? The GCB build VMs don't allow caching between builds.

**Comment by sbuss** [comment]
After speaking off-thread, it appears that I misunderstood how FTL works. I had assumed it cached the source for dependencies, but it actually only caches built artifacts. So there's nothing to be done here.
