### ISSUE TITLE
ext_run.sh doesn't handle spaces in $PWD

### ISSUE THREAD

**Issue by duggelz** [GoogleCloudPlatform/runtimes-common#69]
The flow is like this:

CONFIG_DIR=$(pwd)/.cfg
...
VOLUME_STR="--volumes-from st_container -v $CONFIG_DIR:/cfg"
...
VOLUME_STR=$VOLUME_STR" -v $FULLPATH:/workspace"
...
docker run --rm --entrypoint="$ENTRYPOINT" $VOLUME_STR "$IMAGE_NAME" $CMD_STRING

I will change the script from /bin/sh to /bin/bash and use a bash array to fix this, unless you have an objection to the bash dependency or better idea.

**Comment by duggelz** [comment]
cc @nkubala @dlorenc

**Comment by nkubala** [comment]
I tried to stay away from relying on bash in general for these scripts, but I think it's probably fine here. @dlorenc thoughts?

**Comment by dlorenc** [comment]
Yeah it should be fine for these scripts. We had some stuff running in Alpine images which don't have bash, but these scripts should be fine.
