### ISSUE TITLE
tar --transform is not supported on MacOS

### ISSUE THREAD

**Issue by tanner-bruce** [GoogleCloudPlatform/runtimes-common#719]
When trying to use FTL to build a PHP image on MacOS, it tries to run `tar ... --transform ...`, however `--transform` is not a support option on the MacOS version of `tar`.

**Comment by JonathanRRogers** [comment]
Is it even useful to run an FTL builder on MacOS? The builder depends on platform-specific files including interpreter executables and shared libraries, the MacOS versions of which would never work in a Linux container.
