### ISSUE TITLE
Do not run composer update --lock

### ISSUE THREAD

**Issue by bery** [GoogleCloudPlatform/runtimes-common#742]
Hi

See changes in #724.

Would it be possible to execute something like 

```composer install --no-dev --no-progress --no-suggest --no-interaction```

instead of composer update --lock? 

Composer update has huge memory imprint and currently all builds are failing even for a small symfony PHP application. I cannot imagine any bigger project with many dependencies to build with memory limit around 1Gb for composer update.

Lukas

**Comment by bery** [comment]
Any update on this? It's a serious blocker for us.

**Comment by aaron-prindle** [comment]
This is removed with #749, closing
