### ISSUE TITLE
Typos in README.md

### ISSUE THREAD

**Issue by JonathanRRogers** [GoogleCloudPlatform/runtimes-common#750]
The link to the the 0.13.1 release of the Python ftl.par is incorrect. It should be https://storage.googleapis.com/gcp-container-tools/ftl/python/python-v0.13.1/ftl.par /app/ftl/python_builder.par

In the "Building and Running" section, there is the following sentence: "The most common rules //ftl:node_builder, //ftl:python_builder, //ftl:python_builder." Presumably, it should read, "The most common rules are //ftl:node_builder, //ftl:python_builder, and //ftl:php_builder."

**Comment by aaron-prindle** [comment]
Thanks for pointing these issues out! These are resolved now, closing.
