### ISSUE TITLE
Remove hardcoded config directories from retag scripts in favor of passing configs as command line args

### ISSUE THREAD

**Issue by nkubala** [GoogleCloudPlatform/runtimes-common#96]
The retag job itself takes a list of config files as command line arguments, but all of the other associated scripts (mostly for testing) have the directories hardcoded into them. We should change them to all take in a list of config files as arguments from the command line.

**Comment by sharifelgamal** [comment]
Makes sense, I'll get to this soon.

**Comment by nkubala** [comment]
This has been addressed through a refactor of the retagger code.
